// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyVlOeE1UkiZplCEO7h_BuPNWHuOSbTM',
    appId: '1:767420678827:web:47c56fb0cf9b7c79adedee',
    messagingSenderId: '767420678827',
    projectId: 'demoproject-6d7bd',
    authDomain: 'demoproject-6d7bd.firebaseapp.com',
    storageBucket: 'demoproject-6d7bd.firebasestorage.app',
    measurementId: 'G-91BJ14QEF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvbQYqt6fFd3yXKllPxYnODlgzjuFZaoU',
    appId: '1:767420678827:android:e26eeac772e03c03adedee',
    messagingSenderId: '767420678827',
    projectId: 'demoproject-6d7bd',
    storageBucket: 'demoproject-6d7bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71IyiGtbb3QBFbzFUo7fof1VWVAwdhLc',
    appId: '1:767420678827:ios:1ef5702966cb0358adedee',
    messagingSenderId: '767420678827',
    projectId: 'demoproject-6d7bd',
    storageBucket: 'demoproject-6d7bd.firebasestorage.app',
    iosBundleId: 'com.example.svgEditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71IyiGtbb3QBFbzFUo7fof1VWVAwdhLc',
    appId: '1:767420678827:ios:1ef5702966cb0358adedee',
    messagingSenderId: '767420678827',
    projectId: 'demoproject-6d7bd',
    storageBucket: 'demoproject-6d7bd.firebasestorage.app',
    iosBundleId: 'com.example.svgEditor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtyVlOeE1UkiZplCEO7h_BuPNWHuOSbTM',
    appId: '1:767420678827:web:19cce5c9e60196a0adedee',
    messagingSenderId: '767420678827',
    projectId: 'demoproject-6d7bd',
    authDomain: 'demoproject-6d7bd.firebaseapp.com',
    storageBucket: 'demoproject-6d7bd.firebasestorage.app',
    measurementId: 'G-N0GDSBCHXV',
  );
}
